### ISSUE TITLE
bug: go binding cannot be imported

### ISSUE THREAD

**Issue by wasd96040501** [MDeiml/tree-sitter-markdown#149]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

Go binding cannot build.

Here is my sample code
```go
package main

import (
	"fmt"

	_ "github.com/tree-sitter-grammars/tree-sitter-markdown"
)

func main() {
	fmt.Println("Hello")
}
```

Terminal output:
```bash
➜ go get "github.com/tree-sitter-grammars/tree-sitter-markdown"
go: added github.com/tree-sitter-grammars/tree-sitter-markdown v0.2.3
➜ go mod tidy
go: finding module for package github.com/tree-sitter-grammars/tree-sitter-markdown
go: code.byted.org/flow/mytest imports
	github.com/tree-sitter-grammars/tree-sitter-markdown: module github.com/tree-sitter-grammars/tree-sitter-markdown@latest found (v0.2.3), but does not contain package github.com/tree-sitter-grammars/tree-sitter-markdown
➜ go build
main.go:6:2: no required module provides package github.com/tree-sitter-grammars/tree-sitter-markdown; to add it:
	go get github.com/tree-sitter-grammars/tree-sitter-markdown
```

### Steps To Reproduce/Bad Parse Tree

1. create a new project
2. write code above
3. run in terminal

### Expected Behavior/Parse Tree

build success

**Comment by ObserverOfTime** [comment]
That's a limitation of go that we have not figured out how to solve properly.
A workaround is to add the repo as a git submodule and add this to `go.mod`:
```go.mod
replace github.com/tree-sitter-grammars/tree-sitter-markdown => ./tree-sitter-markdown/bindings/go
```

For context:

`github.com/tree-sitter-grammars/tree-sitter-markdown` doesn't work because there's no module in the root.
`github.com/tree-sitter-grammars/tree-sitter-markdown/bindings/go` doesn't work because it can't access the parents.
