### ISSUE TITLE
Bug: werid indexed list

### ISSUE THREAD

**Issue by black-desk** [MDeiml/tree-sitter-markdown#27]
```markdown
1. a
  1. b
    1. c
    2. d
      1. e
      2. f
```
parsed as:

```
list [0, 0] - [6, 0]
  list_item [0, 0] - [1, 2]
    list_marker_dot [0, 0] - [0, 3]
    paragraph [0, 3] - [1, 2]
  list_item [1, 2] - [6, 0]
    list_marker_dot [1, 2] - [1, 5]
    paragraph [1, 5] - [4, 6]
    list [4, 6] - [6, 0]
      list_item [4, 6] - [5, 6]
        list_marker_dot [4, 6] - [4, 9]
        paragraph [4, 9] - [5, 6]
      list_item [5, 6] - [6, 0]
        list_marker_dot [5, 6] - [5, 9]
        paragraph [5, 9] - [6, 0]
```

which result list mark before c and d have no tshighlight:

![image](https://user-images.githubusercontent.com/29726878/149326841-3e7a38ea-ef56-48c7-930b-3bb6423d0416.png)

**Comment by MDeiml** [comment]
That is actually the right highlighting. Github is parsing it wrong. Try entering your code into https://spec.commonmark.org/dingus/ which is more or less the "reference" implementation of CommonMark markdown. It agrees with what the grammar produced.

I'll still consider changing the behavior of the grammar to match what Github does since that is probably what most people want more than following some random spec they never heard of.

Explaining why this is the proper highlight is a bit complicated, but I'll try in case you're interested (you don't have to read this all):

First of all each line in a list item has to be indented at least as much as the first line in order to be part of the list item. That is why list item b is not counted as a sub list item but as part of the same list as the first one. Try indenting all of your lines one more space to get
```markdown
1. a
   1. b
      1. c
      2. d
         1. e
         2. f
```
Then your file will be parsed as you meant it too. Github actually agrees with me in this point. Notice that if you enter the markdown you supplied it renders as
1. a
  1. b      <- not sub list
    1. c
    2. d
      1. e
      2. f

The second thing going on is that a list item can not be indented more than 3 spaces (relative to the block it is in), so c and d will not be interpreted as list items. This is to make sure it is not misinterpreted as a indented code block (they're not a indented code block in this example for other reasons). Instead c and d will be interpreted as text

Finally e and f DO get interpreted as sub-list item since they are both a) indented at least as far as the first line of the parent list item (b in this case) and b) they are indented less than 4 spaces beyond this point.

**Comment by black-desk** [comment]
Ok, I got it.
